### ISSUE TITLE
"Game does not seem to be a unity project"

### ISSUE THREAD

**Issue by ghost** [Slaynash/VRCTools#15]
When i try to install vrctools using the mod manager it says "Game does not seem to be a unity project. Could no find the libraries to patch."

[Press any key to continue]
help

**Comment by Slaynash** [comment]
Hey
The VRChat mods are currently broken since VRChat v2020.1.1 (Udon & Unity 2018 update).
We are currently working on an universal mod loader for every Unity games, called MelonLoader.
MelonLoader isn't available yet, but you will (only) get your mods back when it will be!
If you want more infos, please join the VRCTools discord: https://discord.gg/rCqKSvR

**Comment by ghost** [comment]
Okay thank you!
